name: Commit Lint 

on: 
  push:
    branches:
      - feature/**
      - hotfix/**

jobs: 
  verifcommit: 
      runs-on: ubuntu-latest
      steps:
        - name: recuperation code 
          uses: actions/checkout@v3

        - name: Commit Linter
          uses: wagoid/commitlint-github-action@v2.0.3
          with:
            configFile: ./commitlint.config.js


    